# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tumblr}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark Wunsch"]
  s.date = %q{2010-03-06}
  s.description = %q{Ruby library and command line utility to work with the Tumblr Blogging Platform, powered by Weary.}
  s.email = %q{mark@markwunsch.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.md",
     "Rakefile",
     "lib/tumblr.rb",
     "test/helper.rb",
     "test/test_tumblr.rb"
  ]
  s.homepage = %q{http://github.com/mwunsch/tumblr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper and command line interface to the Tumblr API.}
  s.test_files = [
    "test/helper.rb",
     "test/test_tumblr.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<weary>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0.9.7"])
    else
      s.add_dependency(%q<weary>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0.9.7"])
    end
  else
    s.add_dependency(%q<weary>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0.9.7"])
  end
end

